# Deprecated: use single_lidar_config.yaml instead
# Keeping file temporarily for backward compatibility.

single_lidar_node:
  ros__parameters:
    # LIDAR device configuration
    device_path: "/dev/lidar_front_center"
    frame_id: "lidar_frame_top_lidar"          # Native sensor frame ID
    topic_name: "/scan"                     # Fused scan topic
    device_type: "LD06"
    serial_baudrate: 230400
    
    # Scan parameters (450 rays matching vendor expectation)
    angle_min: 0.0                    # Start angle (radians)
    angle_max: 6.283185307179586      # End angle (2*PI radians, 360 degrees)
    angle_increment: 0.013962634015954636  # Angular resolution (~0.8 degrees, 2*PI/450)
    range_min: 0.02                   # Minimum range (meters)
    range_max: 15.0                   # Maximum range (meters)
    
    # Motion correction configuration (disabled by default)
    enable_motion_correction: false
    max_correction_time_s: 0.2
    odom_topic: "/sigyn/odom"
