controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    servo_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - joint1
        - joint2
