# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

alias arduino='/home/ros//arduino_2.3.2/arduino-ide&'
alias cb='colcon build --symlink-install'
alias cgcm='ros2 service call /global_costmap/clear_entirely_global_costmap nav2_msgs/srv/ClearEntireCostmap' 
alias clcm='ros2 service call /local_costmap/clear_entirely_local_costmap nav2_msgs/srv/ClearEntireCostmap' 
alias dla="ros2 run --prefix 'gdbserver localhost:3000' line_finder laser_accumulator"
alias fr='ros2 run tf2_tools view_frames'
alias groot='~/Groot2/bin/groot2'
alias lgazebo='clear;ros2 launch linorobot2_gazebo gazebo.launch.py spawn_x:=8 spawn_y:=3'
alias lnav='clear;ros2 launch linorobot2_navigation navigation.launch.py sim:=true'
alias map='clear;ros2 launch base sigyn.launch.py use_sim_time:=false do_rviz:=true make_map:=true'
alias mr='micro-ros-agent serial --dev /dev/ttyACM0 -b 115200'	
alias nav='clear;ros2 launch base sigyn.launch.py use_sim_time:=false do_rviz:=true'
alias pm='ros2 topic pub --rate 10 /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 0.2}}"'
alias rd='rosdep install --from-paths src --ignore-src -r -y'
alias record='rm -r ~/bag;~/sigyn_ws/src/Sigyn/base/scripts/bag_record.sh'
alias redoudev='sudo service udev restart;sudo udevadm control --reload-rules;sudo udevadm trigger'
alias rms='ros2 launch nav2_map_server map_saver_server.launch.py'
#alias roam='DO_RVIZ=true DO_JOYSTICK=false ros2 launch raven_base roam_launch.py'
#alias roam_joy='DO_RVIZ=false DO_JOYSTICK=true ros2 launch raven_base roam_launch.py'
alias rv='rviz2 -d ~/sigyn_ws/src/Sigyn/rviz/config/default_config.rviz'
alias rvs='rviz2 -d ~/sigyn_ws/src/Sigyn/rviz/config/config.rviz'
alias savem='ros2 run nav2_map_server map_saver_cli -f my_map'
#alias s2='source /home/ros/setupRos2.sh'
alias sim='clear;ros2 launch base sigyn.launch.py use_sim_time:=true do_rviz:=true'
alias sp='ssh -YC sigynPiservo'
alias sr='ssh -YC sigyn7900'
alias sv='ssh -YC sigynVision'
alias stele='ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -p speed:=0.25 -p turn:=0.3 -p repeat_rate:=10.0 --remap cmd_vel:=/cmd_vel_keyboard'
alias teensy='ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/teensy_sensor'
alias tele='ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -p speed:=0.25 -p turn:=0.3 -p repeat_rate:=10.0'
alias teles='ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args --remap cmd_vel:=/diff_cont/cmd_vel_unstamped'
alias toggle='ros2 service call /rosbag2_player/toggle_paused rosbag2_interfaces/srv/TogglePaused'

export LINOROBOT2_BASE=2wd
export LINOROBOT2_LASER_SENSOR=rplidar
export LINOROBOT2_DEPTH_SENSOR=realsense

source /opt/ros/jazzy/setup.bash
#source /usr/share/gazebo/setup.bash
source ~/sigyn_ws/install/setup.bash

export CYCLONEDDS_URI="
<CycloneDDS>
   <Domain>
     <General>
        <Interfaces>
	  <NetworkInterface name='eno1' />
        </Interfaces>
                <ParticipantIndex>auto</ParticipantIndex>
                <MaxAutoParticipantIndex>128</MaxAutoParticipantIndex>
    </General>
   </Domain>
</CycloneDDS>"

#export ROS_DOMAIN_ID=0
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
#export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export PICO_SDK_PATH=/home/ros/pico/pico-sdk
export PICO_EXAMPLES_PATH=/home/ros/pico/pico-examples
export PICO_EXTRAS_PATH=/home/ros/pico/pico-extras
export PICO_PLAYGROUND_PATH=/home/ros/pico/pico-playground
export PICO_EXAMPLES_PATH=/home/ros/pico/pico-examples
#export PATH=$PATH:~/.local/bin;/home/ros/.platformio/penv/bin

# Add PlatformIO to PATH
#export PATH="/home/ros/.platformio/penv/bin:$PATH"

# Add Cargo environment to PATH
. "$HOME/.cargo/env"
