<robot xmlns:xacro="http://ros.org/wiki/xacro" name="marker">
    <xacro:macro name="marker" params="name x y rot=0">
        <xacro:property name="length" value="0.2" />
        <xacro:property name="height" value="4" />
        <xacro:property name="width" value="0.1" />
        <xacro:property name="sphere_height" value="${width}" />
        <xacro:property name="x_pos" value="${x + (length / 2)}" />
        <xacro:property name="y_pos" value="${y + (width / 2)}" />
        <link name="${name}">
            <pose> ${x_pos} ${y_pos} ${height / 2} 0 0 ${rot}</pose>
            <visual name="part1">
                <cast_shadows>false</cast_shadows>
                <pose> 0 0 0 0 0 ${rot}</pose>
                <geometry>
                    <box>
                        <size>${length} ${width} ${height}</size>
                    </box>
                </geometry>
                <material>
                    <ambient>1.0 0.0 0.0 1</ambient>
                    <diffuse>0.1 0.1 0.2 1</diffuse>
                    <specular>0 0 0 0</specular>
                    <emissive>0 0 0 1</emissive>
                </material>
            </visual>
            <visual name="part2">
                <cast_shadows>false</cast_shadows>
                <pose> ${(length / 2) + (sphere_height / 2)} 0 ${(sphere_height / 2) - (height / 2)} 0 0 ${rot}</pose>
                <geometry>
                    <sphere>
                        <radius>${sphere_height / 2}</radius>
                    </sphere>
                </geometry>
                <material>
                    <ambient>0.0 0.5 0.0 1</ambient>
                    <diffuse>0.1 0.1 0.2 1</diffuse>
                    <specular>0 0 0 0</specular>
                    <emissive>0 0 0 1</emissive>
                </material>
            </visual>
        </link>
    </xacro:macro>
</robot>