<robot xmlns:xacro="http://ros.org/wiki/xacro" name="foo3">
  <xacro:include filename="marker.xacro" />
  <xacro:include filename="wall.xacro" />
  <sdf version="1.4">
    <model name="robot_home">
      <static>true</static>
      <xacro:property name="wall_width" value="4" />

      <xacro:marker name="x_origin_marker" x="0.2" y="0.3" />

      <!-- big outer walls-->
      <xacro:property name="house_ew_length" value="${(50*12)+7}" />
      <xacro:property name="house_ns_length" value="${(49*12)+3 - 10}" />

      <xacro:wall name="north_wall"
        length_in="${wall_width}"
        width_in="${house_ew_length}"
        x_in="${-wall_width}"
        y_in="0"
      />

      <xacro:wall name="south_wall"
        length_in="${wall_width}"
        width_in="${house_ew_length}"
        x_in="${house_ns_length}"
        y_in="0"
      />

      <xacro:wall name="east_wall"
        length_in="${house_ns_length}"
        width_in="${wall_width}"
        x_in="0"
        y_in="${house_ew_length - wall_width}"
      />

      <xacro:property name="len_north_atrium_wall" value="${(30*12)+11}" />
      <xacro:property name="pos_north_atrium_wall" value="${(19*12)+1}" />

      <xacro:wall name="north_atrium_wall"
        length_in="${wall_width}"
        width_in="${len_north_atrium_wall + wall_width}"
        x_in="${pos_north_atrium_wall}"
        y_in="0"
      />

      <!-- hobby room -->
      <xacro:property name="len_hobby_east_wall_1" value="${(13*12)+9}" />
      <xacro:property name="pos_hobby_east_wall" value="${(30*12)+11}" />
      <xacro:wall name="hobby_east_wall_1"
        width_in="${wall_width}"
        length_in="${len_hobby_east_wall_1}"
        y_in="${pos_hobby_east_wall}"
        x_in="0"
      />

      <xacro:property name="len_hobby_east_wall_2" value="${(2*12)+8}" />
      <xacro:wall name="hobby_east_wall_2"
        length_in="${len_hobby_east_wall_2}"
        width_in="${wall_width}"
        y_in="${pos_hobby_east_wall}"
        x_in="${len_hobby_east_wall_1+(2*12)+8}"
      />

      <xacro:property name="len_hobby_west_wall" value="${(19*12)+1}" />
      <xacro:property name="pos_hobby_west_wall" value="${(20*12)+7}" />
      <xacro:wall name="hobby_west_wall"
        width_in="4"
        length_in="${len_hobby_west_wall}"
        y_in="${pos_hobby_west_wall}"
        x_in="0"
      />


      <!-- living room -->
      <xacro:property name="len_kitchen_lr_divider" value="${(15*12)+3}" />
      <xacro:property name="x_pos_kitchen_lr_divider" value="${(13*12)+4}" />
      <xacro:property name="y_pos_kitchen_lr_divider" value="${(35*12)}" />

      <xacro:wall name="kitchen_lr_divider"
        width_in="${len_kitchen_lr_divider}"
        length_in="${wall_width}"
        x_in="${x_pos_kitchen_lr_divider}"
        y_in="${y_pos_kitchen_lr_divider}"
      />

      <!-- kitchen room -->
      <xacro:property name="len_master_br_kitchen_divider" value="${(15*12)+4}" />
      <xacro:property name="x_pos_master_br_kitchen_divider" value="${(34*12)}" />
      <xacro:property name="y_pos_master_br_kitchen_divider" value="${(34*12)+11}" />
      <xacro:wall
        name="master_br_kitchen_divider"
        width_in="${len_master_br_kitchen_divider}"
        length_in="${wall_width}"
        x_in="${x_pos_master_br_kitchen_divider}"
        y_in="${y_pos_master_br_kitchen_divider}"
      />

      <!-- master bedroom closet -->
      <xacro:property name="len_master_br_closet_ew" value="${6*12}" />
      <xacro:property name="len_master_br_closet_ew_long" value="${len_master_br_closet_ew + (2*wall_width)}" />
      <xacro:property name="x_pos_master_br_closet_ew_long" value="${(37*12)+4}" />
      <xacro:property name="y_pos_master_br_closet_ew_long" value="${(31*12)+7}" />
      <xacro:wall
        name="master_br_closet_ew_long"
        length_in="${wall_width}"
        width_in="${len_master_br_closet_ew_long}"
        x_in="${x_pos_master_br_closet_ew_long}"
        y_in="${y_pos_master_br_closet_ew_long}"
      />

      <xacro:property name="len_master_br_closet_ns" value="${(5*12)}" />
      <xacro:property name="x_pos_master_br_closet_ns_east" value="${x_pos_master_br_closet_ew_long + wall_width}" />
      <xacro:property name="y_pos_master_br_closet_ns_east" value="${y_pos_master_br_closet_ew_long + len_master_br_closet_ew + wall_width}" />
      <xacro:wall
        name="master_br_closet_ns_east"
        length_in="${len_master_br_closet_ns}"
        width_in="${wall_width}"
        x_in="${x_pos_master_br_closet_ns_east}"
        y_in="${y_pos_master_br_closet_ns_east}"
      />

      <xacro:property name="x_pos_master_br_closet_ns_west" value="${x_pos_master_br_closet_ew_long + wall_width}" />
      <xacro:property name="y_pos_master_br_closet_ns_west" value="${y_pos_master_br_closet_ew_long}" />
      <xacro:wall name="master_br_closet_ns_west"
        width_in="${wall_width}"
        length_in="${len_master_br_closet_ns}"
        x_in="${x_pos_master_br_closet_ns_west}"
        y_in="${y_pos_master_br_closet_ns_west}"
      />

      <xacro:property name="len_master_br_closet_ew_short_east" value="${(2*12)+1}" />
      <xacro:property name="x_pos_master_br_closet_ew_short_east" value="${x_pos_master_br_closet_ns_east + len_master_br_closet_ns}" />
      <xacro:property name="y_pos_master_br_closet_ew_short_east" value="${y_pos_master_br_closet_ns_east - len_master_br_closet_ew_short_east + wall_width}" />
      <xacro:wall
        name="master_br_closet_ew_short_east"
        width_in="${len_master_br_closet_ew_short_east}"
        length_in="${wall_width}"
        x_in="${x_pos_master_br_closet_ew_short_east}"
        y_in="${y_pos_master_br_closet_ew_short_east}"
      />

      <xacro:property name="len_master_br_closet_ew_short_west" value="${(2*12)+1 + wall_width}" />
      <xacro:property name="x_pos_master_br_closet_ew_short_west" value="${x_pos_master_br_closet_ew_short_east}" />
      <xacro:property name="y_pos_master_br_closet_ew_short_west" value="${y_pos_master_br_closet_ns_west}" />
      <xacro:wall
        name="master_br_closet_ew_short_west"
        width_in="${len_master_br_closet_ew_short_west}"
        length_in="${wall_width}"
        x_in="${x_pos_master_br_closet_ew_short_west}"
        y_in="${y_pos_master_br_closet_ew_short_west}"
      />

      <xacro:property name="len_master_br_closet_ns_west_to_door" value="${(1*12)+6 - wall_width}" />
      <xacro:property name="x_pos_master_br_closet_ns_west_to_door" value="${x_pos_master_br_closet_ew_short_west + wall_width}" />
      <xacro:property name="y_pos_master_br_closet_ns_west_to_door" value="${y_pos_master_br_closet_ew_short_west + len_master_br_closet_ew_short_west - wall_width}" />
      <xacro:wall
        name="master_br_closet_ns_west_to_door"
        width_in="${wall_width}"
        length_in="${len_master_br_closet_ns_west_to_door}"
        x_in="${x_pos_master_br_closet_ns_west_to_door}"
        y_in="${y_pos_master_br_closet_ns_west_to_door}"
      />

      <!-- master bedroom vanity -->
      <xacro:property name="master_br_vanity_width_in" value="48" />
      <xacro:property name="len_master_br_vanity_wall" value="${(2*12)}"  />
      <xacro:property name="x_pos_master_br_vanity_wall" value="${house_ns_length - len_master_br_vanity_wall}" />
      <xacro:property name="y_pos_master_br_vanity_wall_west" value="${(33*12)+6}" />
      <xacro:wall
        name="master_br_vanity_wall_east"
        width_in="${wall_width}"
        length_in="${len_master_br_vanity_wall}"
        x_in="${x_pos_master_br_vanity_wall}"
        y_in="${y_pos_master_br_closet_ns_east}"
      />

      <xacro:wall
        name="master_br_vanity_wall_west"
        width_in="${wall_width}"
        length_in="${len_master_br_vanity_wall}"
        x_in="${x_pos_master_br_vanity_wall}"
        y_in="${y_pos_master_br_closet_ns_east - master_br_vanity_width_in - wall_width}"
      />

      <link 
        name="master_br_vanity">
        <xacro:property  name="master_br_vanity_length_in" value="20" />
        <xacro:property
          name="master_br_vanity_height_in" value="32" />
        <xacro:property
          name="master_br_vanity_pose_x"
          value="${0.0254*(house_ns_length - (master_br_vanity_length_in/2))}" />
        <pose>
          ${master_br_vanity_pose_x}
          ${0.0254 * (y_pos_master_br_closet_ns_east - (master_br_vanity_width_in / 2))}
          ${(0.0254 * (master_br_vanity_height_in / 2))}
          0
          0
          0
        </pose>
        <collision name="collision">
          <geometry>
            <box>
              <size>
                ${master_br_vanity_length_in * 0.0254} 
                ${master_br_vanity_width_in * 0.0254}
                ${master_br_vanity_height_in * 0.0254}</size>
            </box>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>false</cast_shadows>
          <geometry>
            <box>
              <size>${master_br_vanity_length_in* 0.0254} 
                ${master_br_vanity_width_in * 0.0254}
                ${master_br_vanity_height_in * 0.0254}</size>
            </box>
          </geometry>
          <material>
            <ambient>1.0 0.0 0.0 1</ambient>
            <diffuse>0.1 0.1 0.2 1</diffuse>
            <specular>0 0 0 0</specular>
            <emissive>0 0 0 1</emissive>
          </material>
        </visual>
      </link>

      <!-- master br / guest shower divider wall-->
      <xacro:property name="len_master_br_guest_shower_divider" value="${(8*12)+4}"/>
      <xacro:property name="x_pos_master_br_guest_shower_divider" value="${house_ns_length - len_master_br_guest_shower_divider}"/>
      <xacro:property name="y_pos_master_br_guest_shower_divider" value="${(28*12)+4}"/>
      <xacro:wall
        name="master_br_guest_shower_divider"
        width_in="${8}"
        length_in="${len_master_br_guest_shower_divider}"
        x_in="${x_pos_master_br_guest_shower_divider}"
        y_in="${y_pos_master_br_guest_shower_divider}"
      />

      <!-- guess bathroom-->
      <xacro:property name="len_guest_bath_north_wall" value="${(5*12)+2 + wall_width}" />
      <xacro:property name="x_pos_guest_bath_north_wall" value="${(39*12)+9}"/>
      <xacro:property name="y_pos_guest_bath_north_wall" value="${(26*12)+1}"/>
      <xacro:wall
        name="guest_bath_north_wall"
        width_in="${len_guest_bath_north_wall}"
        length_in="${wall_width}"
        x_in="${x_pos_guest_bath_north_wall}"
        y_in="${y_pos_guest_bath_north_wall}"
      />

      <xacro:property name="len_guest_bath_closet_west_wall" value="${(2*12)+5}" />
      <xacro:property name="x_guest_bath_closet_east_wall" value="${x_pos_guest_bath_north_wall - len_guest_bath_closet_west_wall}"/>
      <xacro:property name="y_guest_bath_closet_east_wall" value="${y_pos_guest_bath_north_wall}"/>
      <xacro:wall
        name="guest_bath_closet_east_wall"
        length_in="${(2*12)+5+4}"
        width_in="${wall_width}"
        x_in="${x_guest_bath_closet_east_wall}"
        y_in="${y_guest_bath_closet_east_wall}"
      />

      <xacro:property name="len_guest_bath_west_wall1" value="${(5*12)+10.5}" />
      <xacro:property name="x_guest_bath_west_wall1" value="${(37*12)+4 + wall_width}"/>
      <xacro:property name="y_guest_bath_west_wall1" value="${(22*12)+11}"/>
      <xacro:wall
        name="guest_bath_west_wall1"
        length_in="${len_guest_bath_west_wall1}"
        width_in="${wall_width}"
        x_in="${x_guest_bath_west_wall1}"
        y_in="${y_guest_bath_west_wall1}"
      />

      <xacro:property name="len_guest_bath_west_wall2" value="${(4.0*12.0)+10.5}" />
      <xacro:property name="x_guest_bath_west_wall2" value="${house_ns_length - len_guest_bath_west_wall2}"/>
      <xacro:property name="y_guest_bath_west_wall2" value="${(20*12)+8}"/>
      <xacro:wall
        name="guest_bath_west_wall2"
        length_in="${len_guest_bath_west_wall2}"
        width_in="${wall_width}"
        x_in="${x_guest_bath_west_wall2}"
        y_in="${y_guest_bath_west_wall2}"
      />

      <xacro:wall
        name="guest_bathtub_end_wall"
        length_in="${wall_width}"
        width_in="${(2*12) + 9}"
        x_in="${x_guest_bath_west_wall2 - wall_width}"
        y_in="${y_guest_bath_west_wall2}"
      />

      <link
        name="guest_bath_vanity">
        <xacro:property
          name="guest_bath_vanity_length_in" value="${(5*12)+6}" />
        <xacro:property
          name="guest_bath_vanity_width_in" value="${(1*12)+10}" />
        <xacro:property
          name="guest_bath_vanity_height_in" value="32" />
        <pose>
          ${0.0254 * (x_pos_guest_bath_north_wall + (guest_bath_vanity_length_in/2))}
          ${0.0254 * (y_pos_master_br_guest_shower_divider - guest_bath_vanity_width_in + (guest_bath_vanity_width_in / 2))}
          ${0.0254 * (guest_bath_vanity_height_in / 2)}
          0
          0
          0
        </pose>
        <collision name="collision">
          <geometry>
            <box>
              <size>
                ${guest_bath_vanity_length_in * 0.0254} 
                ${guest_bath_vanity_width_in * 0.0254}
                ${guest_bath_vanity_height_in * 0.0254}</size>
            </box>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>false</cast_shadows>
          <geometry>
            <box>
              <size>${guest_bath_vanity_length_in* 0.0254} 
                ${guest_bath_vanity_width_in * 0.0254}
                ${guest_bath_vanity_height_in * 0.0254}</size>
            </box>
          </geometry>
          <material>
            <ambient>0.0 0.0 0. 1</ambient>
            <diffuse>0.1 0.1 0.2 1</diffuse>
            <specular>0 0 0 0</specular>
            <emissive>0 0 0 1</emissive>
          </material>
        </visual>
      </link>

      <link
        name="guest_bathtub">
        <xacro:property
          name="guest_bathtub_length_in" value="${(4*12)+10.5}" />
        <xacro:property
          name="guest_bathtub_width_in" value="${(2*12)+5}" />
        <xacro:property
          name="guest_bathtub_height_in" value="24" />
        <pose>
          ${0.0254 * (x_guest_bath_west_wall2 + (guest_bathtub_length_in/2))}
          ${0.0254 * (y_guest_bath_west_wall2 + (guest_bathtub_width_in/2))}
          ${0.0254 * (guest_bathtub_height_in / 2)}
          0
          0
          0
        </pose>
        <collision name="collision">
          <geometry>
            <box>
              <size>
                ${guest_bathtub_length_in * 0.0254} 
                ${guest_bathtub_width_in * 0.0254}
                ${guest_bathtub_height_in * 0.0254}</size>
            </box>
          </geometry>
        </collision>
        <visual name="visual">
          <cast_shadows>false</cast_shadows>
          <geometry>
            <box>
              <size>${guest_bathtub_length_in* 0.0254} 
                ${guest_bathtub_width_in * 0.0254}
                ${guest_bathtub_height_in * 0.0254}</size>
            </box>
          </geometry>
          <material>
            <ambient>0.9 0.9 0.9 1</ambient>
            <diffuse>0.1 0.1 0.2 1</diffuse>
            <specular>0 0 0 0</specular>
            <emissive>0 0 0 1</emissive>
          </material>
        </visual>
      </link>

      <!-- music room -->
      <xacro:property name="len_music_west_wall" value="${(10*12)+9}" />
      <xacro:property name="x_pos_music_west_wall" value="${house_ns_length - len_music_west_wall}" />
      <xacro:property name="y_pos_music_west_wall" value="${(10*12)+4}" />
      <xacro:wall 
        name="music_west_wall"
        length_in="${len_music_west_wall}"
        width_in="${wall_width}"
        x_in="${x_pos_music_west_wall}"
        y_in="${y_pos_music_west_wall}"
      />

      <xacro:property  name="len_music_north_ew_1" value="${(2*12)+8+wall_width}" />
      <xacro:property name="y_pos_music_north_ew_1" value="${y_guest_bath_west_wall1 - len_music_north_ew_1 + wall_width}" />
      <xacro:wall 
        name="music_north_ew_1"
        length_in="${wall_width}"
        width_in="${len_music_north_ew_1}"
        x_in="${x_pos_master_br_closet_ew_long}"
        y_in="${y_pos_music_north_ew_1}"
      />

      <xacro:property  name="len_music_north_ew_2" value="${(7*12)+5}" />
      <xacro:wall 
        name="music_north_ew_2"
        length_in="${wall_width}"
        width_in="${len_music_north_ew_2}"
        x_in="${x_pos_master_br_closet_ew_long}"
        y_in="${y_pos_music_west_wall}"
      />

      <!-- cat room -->
      <xacro:property 
        name="len_cat_computer_west_wall" value="${(24*12)+4}"
      />
      <xacro:wall 
        name="cat_computer_west_wall"
        length_in="${len_cat_computer_west_wall}"
        width_in="${wall_width}"
        x_in="${house_ns_length - len_cat_computer_west_wall}"
        y_in="${0}"
      />

      <xacro:property name="len_cat_north_ns" value="${(4*12)+10}" />
      <xacro:property name="pos_x_cat_north_ns" value="${house_ns_length - ((11*12)+7 + wall_width)}" />
      <xacro:wall 
        name="cat_north_ns"
        length_in="${wall_width}"
        width_in="${len_cat_north_ns}"
        x_in="${pos_x_cat_north_ns}"
        y_in="${wall_width}"
      />

      <!-- west hall closet -->
      <xacro:property  name="len_closet_west_hall_back" value="${(4*12)+6}" />
      <xacro:property name="pos_x_closet_west_hall_back" value="${pos_x_cat_north_ns - ((2*12)+1)}" />
      <xacro:property name="pos_y_closet_west_hall_back" value="${wall_width + len_cat_north_ns}" />
      <xacro:wall 
        name="closet_west_hall_back"
        length_in="${len_closet_west_hall_back}"
        width_in="${wall_width}"
        x_in="${pos_x_closet_west_hall_back}"
        y_in="${pos_y_closet_west_hall_back}"
      />

      <xacro:property name="len_closet_east_wall_north" value="${(2*12)+5}" />
      <xacro:property name="pos_x_closet_east_wall_north" value="${pos_x_closet_west_hall_back + len_closet_west_hall_back}" />
      <xacro:property name="pos_y_closet_east_wall_north" value="${pos_y_closet_west_hall_back}" />
      <xacro:wall 
        name="closet_east_wall_north"
        length_in="${wall_width}"
        width_in="${len_closet_east_wall_north}"
        x_in="${pos_x_closet_east_wall_north}"
        y_in="${pos_y_closet_east_wall_north}"
      />

      <xacro:property  name="len_closet_west_hall_north" value="${(3*12)+8}" />
      <xacro:property name="pos_x_closet_west_hall_north" value="${pos_x_closet_west_hall_back - wall_width}" />
      <xacro:property name="pos_y_closet_west_hall_north" value="${pos_y_closet_west_hall_back}" />
      <xacro:wall 
        name="closet_west_hall_north"
        length_in="${wall_width}"
        width_in="${len_closet_west_hall_north}"
        x_in="${pos_x_closet_west_hall_north}"
        y_in="${pos_y_closet_west_hall_north}"
      />

      <!-- computer room -->
      <xacro:property name="len_computer_north" value="${(12*12)}" />
      <xacro:property name="x_pos_computer_north" value="${(23*12)+9}" />
      <xacro:wall 
        name="computer_north"
        length_in="${wall_width}"
        width_in="${len_computer_north}"
        x_in="${x_pos_computer_north}"
        y_in="${0}"
      />

      <xacro:property  name="len_computer_east_wall" value="${(10*12)}" />
      <xacro:property name="y_pos_computer_east_wall" value="${len_computer_north - wall_width}" />
      <xacro:wall 
        name="computer_east_wall"
        length_in="${len_computer_east_wall}"
        width_in="${wall_width}"
        x_in="${x_pos_computer_north + wall_width}"
        y_in="${y_pos_computer_east_wall}"
      />

      <!-- long hallway north wall -->
      <xacro:property  name="len_long_hall_north" value="${(19*12)+7}" />
      <xacro:wall 
        name="long_hall_north"
        length_in="${wall_width}"
        width_in="${len_long_hall_north}"
        x_in="${x_pos_master_br_kitchen_divider}"
        y_in="${y_pos_computer_east_wall}"
      />

      <!-- atrium east wall -->
      <xacro:property  name="len_atrium_east_wall" value="${(14*12)+7}" />
      <xacro:property name="x_pos_atrium_east_wall" value="${x_pos_master_br_kitchen_divider - len_atrium_east_wall}" />
      <xacro:property name="y_pos_atrium_east_wall" value="${(30*12)+11}" />
      <xacro:wall 
        name="atrium_east_wall"
        length_in="${len_atrium_east_wall}"
        width_in="${wall_width}"
        x_in="${x_pos_atrium_east_wall}"
        y_in="${y_pos_atrium_east_wall}"
      />

    </model>
  </sdf>
</robot>