bluetooth_joystick:
  ros__parameters:
    device_name: "/dev/input/nimbus_steelseries"
    cmdvel_topic: "cmd_vel_joystick"
    deadzone_percent: 5.0
    scale_x: 0.25
    scale_z: 0.25
    gripper_topic: "cmd_vel_gripper"
    cmdvel_message_rate: 10
    gripper_message_rate: 600
    joystick_message_rate: 100
    gripper_open_value: 1000
    gripper_close_value: -1000
    cmdvel_twister_topic: "cmd_vel_testicle_twister"
