#!/usr/bin/env python3
"""Nav2 Debug Monitor - Comprehensive navigation debugging.

Subscribes to all critical Nav2 topics and logs:
- Goals sent to planner/controller
- Paths generated by planner
- Current robot pose
- Docking staging poses
- TF transforms

This provides a complete picture of what Nav2 is trying to do and why.
"""

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import PoseStamped, PoseWithCovarianceStamped
from nav_msgs.msg import Path
from nav2_msgs.action import NavigateToPose
from rclpy.action import ActionClient
import math


class Nav2DebugMonitor(Node):
    def __init__(self):
        super().__init__('nav2_debug_monitor')
        
        # Track state
        self._last_goal = None
        self._last_robot_pose = None
        self._last_plan = None
        self._goal_count = 0
        
        # Subscribe to navigation goals
        self.create_subscription(
            PoseStamped,
            '/goal_pose',
            self._goal_pose_callback,
            10
        )
        
        # Subscribe to robot pose
        self.create_subscription(
            PoseWithCovarianceStamped,
            '/amcl_pose',
            self._amcl_pose_callback,
            10
        )
        
        # Subscribe to global plan
        self.create_subscription(
            Path,
            '/plan',
            self._plan_callback,
            10
        )
        
        # Subscribe to local plan
        self.create_subscription(
            Path,
            '/local_plan',
            self._local_plan_callback,
            10
        )
        
        # Subscribe to docking staging pose if published
        self.create_subscription(
            PoseStamped,
            '/staging_pose',
            self._staging_pose_callback,
            10
        )
        
        self.get_logger().info("=" * 80)
        self.get_logger().info("🔍 NAV2 DEBUG MONITOR ACTIVE")
        self.get_logger().info("   Monitoring: /goal_pose, /amcl_pose, /plan, /local_plan, /staging_pose")
        self.get_logger().info("=" * 80)
    
    def _goal_pose_callback(self, msg: PoseStamped):
        """Log navigation goals with full details."""
        self._goal_count += 1
        self._last_goal = msg
        
        x = msg.pose.position.x
        y = msg.pose.position.y
        z = msg.pose.position.z
        
        # Extract yaw from quaternion
        qx = msg.pose.orientation.x
        qy = msg.pose.orientation.y
        qz = msg.pose.orientation.z
        qw = msg.pose.orientation.w
        
        # Convert quaternion to yaw
        siny_cosp = 2 * (qw * qz + qx * qy)
        cosy_cosp = 1 - 2 * (qy * qy + qz * qz)
        yaw = math.atan2(siny_cosp, cosy_cosp)
        yaw_deg = math.degrees(yaw)
        
        self.get_logger().info("")
        self.get_logger().info("=" * 80)
        self.get_logger().info(f"🎯 GOAL #{self._goal_count} RECEIVED")
        self.get_logger().info(f"   Frame: {msg.header.frame_id}")
        self.get_logger().info(f"   Position: x={x:.4f}m, y={y:.4f}m, z={z:.4f}m")
        self.get_logger().info(f"   Orientation: x={qx:.4f}, y={qy:.4f}, z={qz:.4f}, w={qw:.4f}")
        self.get_logger().info(f"   Yaw: {yaw:.4f} rad ({yaw_deg:.2f}°)")
        
        if self._last_robot_pose:
            # Calculate distance from current pose to goal
            rx = self._last_robot_pose.pose.pose.position.x
            ry = self._last_robot_pose.pose.pose.position.y
            dist = math.sqrt((x - rx)**2 + (y - ry)**2)
            
            # Calculate angle to goal
            angle_to_goal = math.atan2(y - ry, x - rx)
            angle_to_goal_deg = math.degrees(angle_to_goal)
            
            # Extract robot yaw
            rqx = self._last_robot_pose.pose.pose.orientation.x
            rqy = self._last_robot_pose.pose.pose.orientation.y
            rqz = self._last_robot_pose.pose.pose.orientation.z
            rqw = self._last_robot_pose.pose.pose.orientation.w
            rsiny_cosp = 2 * (rqw * rqz + rqx * rqy)
            rcosy_cosp = 1 - 2 * (rqy * rqy + rqz * rqz)
            robot_yaw = math.atan2(rsiny_cosp, rcosy_cosp)
            robot_yaw_deg = math.degrees(robot_yaw)
            
            # Calculate rotation needed
            rotation_needed = yaw - robot_yaw
            # Normalize to [-pi, pi]
            while rotation_needed > math.pi:
                rotation_needed -= 2 * math.pi
            while rotation_needed < -math.pi:
                rotation_needed += 2 * math.pi
            rotation_needed_deg = math.degrees(rotation_needed)
            
            self.get_logger().info("")
            self.get_logger().info("📍 CURRENT ROBOT STATE:")
            self.get_logger().info(f"   Position: x={rx:.4f}m, y={ry:.4f}m")
            self.get_logger().info(f"   Yaw: {robot_yaw:.4f} rad ({robot_yaw_deg:.2f}°)")
            self.get_logger().info("")
            self.get_logger().info("📐 GOAL RELATIVE TO ROBOT:")
            self.get_logger().info(f"   Distance: {dist:.4f}m")
            self.get_logger().info(f"   Bearing: {angle_to_goal:.4f} rad ({angle_to_goal_deg:.2f}°)")
            self.get_logger().info(f"   Rotation needed: {rotation_needed:.4f} rad ({rotation_needed_deg:.2f}°)")
            
            # Determine if rotation is needed
            if abs(rotation_needed_deg) > 10:
                self.get_logger().warn(f"   ⚠️  LARGE ROTATION REQUIRED: {rotation_needed_deg:.1f}°")
                if abs(rotation_needed_deg) > 90:
                    self.get_logger().error(f"   ❌ GOAL IS BEHIND ROBOT (>90° rotation needed)!")
        else:
            self.get_logger().warn("   ⚠️  No robot pose available yet")
        
        self.get_logger().info("=" * 80)
    
    def _amcl_pose_callback(self, msg: PoseWithCovarianceStamped):
        """Track current robot pose."""
        self._last_robot_pose = msg
    
    def _plan_callback(self, msg: Path):
        """Log global plan details."""
        if not msg.poses:
            return
        
        self._last_plan = msg
        
        start = msg.poses[0]
        end = msg.poses[-1]
        
        self.get_logger().info("")
        self.get_logger().info("🗺️  GLOBAL PLAN GENERATED")
        self.get_logger().info(f"   Waypoints: {len(msg.poses)}")
        self.get_logger().info(f"   Start: x={start.pose.position.x:.3f}, y={start.pose.position.y:.3f}")
        self.get_logger().info(f"   End: x={end.pose.position.x:.3f}, y={end.pose.position.y:.3f}")
        
        # Calculate total path length
        total_dist = 0.0
        for i in range(1, len(msg.poses)):
            p1 = msg.poses[i-1].pose.position
            p2 = msg.poses[i].pose.position
            total_dist += math.sqrt((p2.x - p1.x)**2 + (p2.y - p1.y)**2)
        
        self.get_logger().info(f"   Path length: {total_dist:.3f}m")
    
    def _local_plan_callback(self, msg: Path):
        """Log local plan (less verbose)."""
        if not msg.poses or len(msg.poses) < 5:
            return
        
        # Only log every 50th local plan to avoid spam
        if not hasattr(self, '_local_plan_count'):
            self._local_plan_count = 0
        self._local_plan_count += 1
        
        if self._local_plan_count % 50 == 0:
            self.get_logger().debug(f"Local plan: {len(msg.poses)} points")
    
    def _staging_pose_callback(self, msg: PoseStamped):
        """Log docking staging poses."""
        x = msg.pose.position.x
        y = msg.pose.position.y
        
        # Extract yaw
        qz = msg.pose.orientation.z
        qw = msg.pose.orientation.w
        yaw = math.atan2(2 * qw * qz, 1 - 2 * qz * qz)
        yaw_deg = math.degrees(yaw)
        
        self.get_logger().info("")
        self.get_logger().info("🚪 DOCKING STAGING POSE CALCULATED")
        self.get_logger().info(f"   Position: x={x:.4f}m, y={y:.4f}m")
        self.get_logger().info(f"   Yaw: {yaw:.4f} rad ({yaw_deg:.2f}°)")
        
        if self._last_robot_pose:
            rx = self._last_robot_pose.pose.pose.position.x
            ry = self._last_robot_pose.pose.pose.position.y
            dist = math.sqrt((x - rx)**2 + (y - ry)**2)
            self.get_logger().info(f"   Distance from robot: {dist:.4f}m")


def main(args=None):
    rclpy.init(args=args)
    node = Nav2DebugMonitor()
    
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
