perimeter_roamer_v2:
  ros__parameters:
    # Speed settings - optimized for house navigation
    forward_speed: 0.12           # Normal forward speed (conservative)
    turn_speed: 0.25              # Turning speed (conservative)
    narrow_space_speed: 0.05      # Speed in narrow spaces (very slow)
    
    # Wall following parameters
    wall_distance_setpoint: 1.0   # Desired distance from wall for room patrol (1 meter)
    hallway_distance_setpoint: 0.5 # Desired distance from wall for hallway (0.5 meter)
    wall_following_gain: 0.4      # Wall following gain (conservative)
    kp_angular: 1.5               # Proportional gain for angular control
    max_angular_speed: 0.6        # Maximum angular velocity (conservative)
    
    # Robot physical dimensions (from your specifications)
    robot_radius: 0.2286          # 0.2286m radius as specified
    robot_diameter: 0.88          # Full diameter
    
    # Space classification thresholds
    doorway_width_threshold: 0.8  # Spaces narrower than this are doorways
    narrow_hallway_threshold: 1.2 # Spaces narrower than this are narrow hallways  
    very_narrow_threshold: 0.6    # Extremely tight spaces
    room_detection_threshold: 2.0 # Minimum space to be considered a room
    
    # LIDAR-based safety (no costmap dependency)
    min_obstacle_distance: 0.8    # Absolute minimum safe distance (CENTER distance) - robot stops when center distance < this
    comfortable_distance: 1.5     # Preferred clearance distance (CENTER distance) - robot slows down when center distance < this
    
    # Control parameters
    control_frequency: 10.0
    base_frame: "base_link"
    odom_frame: "odom"
    
    # Frame handling parameters
    use_sim_time: false  # Set to true when using simulation
    transform_timeout: 0.1  # Timeout for transform lookups
    
    # Topic names
    cmd_vel_topic: "/cmd_vel"
    scan_topic: "/scan"
    odom_topic: "/odom"
    
    # Recovery behavior
    recovery_backup_speed: -0.08  # Slow backup speed
    recovery_backup_time: 1.5     # Time to back up
    recovery_turn_time: 2.0       # Time to turn during recovery
    
    # Stuck detection
    stuck_timeout: 8.0            # Time before considering robot stuck
    stuck_distance_threshold: 0.03 # Minimum movement to not be stuck

    # Doorway navigation parameters
    doorway_approach_distance: 0.6      # Distance to start centering approach
    doorway_centering_tolerance: 0.05   # How centered we need to be (±5cm)
    doorway_alignment_angle_tolerance: 0.1  # Angular tolerance in radians (~6°)
    doorway_detection_threshold: 1.5    # Distance threshold for doorway detection
    wall_disappearance_threshold: 2.0   # Distance threshold for wall disappearance
    post_doorway_forward_time: 3.0      # Time to move forward after doorway
    turn_duration: 2.5                  # Time for 90-degree turn

    # Room patrol parameters
    room_patrol_speed: 0.12       # Speed for room patrol
    room_patrol_distance: 1.0     # Distance to maintain from walls in rooms
    room_patrol_turn_angle: 0.3   # Turn angle when too close to wall (radians)
    
    # Hallway navigation parameters
    hallway_speed: 0.10           # Speed for hallway navigation
    hallway_centering_gain: 0.8   # Gain for hallway centering control 