perimeter_roamer:
  ros__parameters:
    # Speeds
    forward_speed: 0.2
    turn_speed: 0.4
    max_angular_speed: 1.0

    # Wall Following
    wall_distance_setpoint: 0.5    # Corrected from wall_follow_distance
    wall_following_gain: 0.3       # Corrected from wall_dist_error_gain
    kp_angular: 1.5                # Proportional gain for angular correction
    wall_presence_threshold: 0.25 # How close a wall needs to be to be considered "present"

    # Obstacle Detection (Costmap-based)
    costmap_check_distance: 0.5
    costmap_check_points_front: 5
    robot_width: 0.46
    costmap_lethal_threshold: 254
    costmap_inscribed_threshold: 99 # Default threshold for non-doorway collisions

    # Robot physical dimensions & Safety
    robot_radius: 0.23
    safety_bubble_distance: 0.3    # Corrected from safety_bubble_radius

    # Corner Collision Avoidance
    corner_lookahead_distance: 0.3
    corner_check_angle: 0.785      # 45 degrees in radians

    # State Machine & Control
    control_frequency: 10.0

    # Stuck Detection
    stuck_timeout: 5.0
    stuck_distance_threshold: 0.02
    stuck_angle_threshold: 0.1     # In radians (~5.7 degrees)
    recovery_backup_speed: -0.1
    recovery_backup_time: 2.0
    recovery_turn_angle: 1.57      # 90 degrees in radians
    recovery_turn_time: 2.5

    # --- Doorway Navigation Parameters ---
    doorway_detection_width: 1.2    # Max width to be considered a doorway (m)
    doorway_forward_speed: 0.1     # Slower speed for safety
    doorway_kp_angular: 1.5         # Proportional gain for centering in the doorway
    doorway_aim_distance: 1.0       # How far ahead to project the target point
    doorway_scan_angle_start: 0.785 # 45 degrees in radians
    doorway_scan_angle_end: 2.356   # 135 degrees in radians

    # --- State-Dependent Safety Parameters (Doorway) ---
    doorway_safety_bubble_distance: 0.15 # meters
    doorway_costmap_check_distance: 0.25 # meters
    doorway_cost_threshold: 80     # 0-100
    doorway_detection_skew: 0.4 # meters
    doorway_max_angle_for_full_speed: 0.35 # radians (~20 degrees)
    doorway_commit_time: 2.0 # seconds to commit to a doorway before re-evaluating

    # TF / Frames
    robot_base_frame: "base_link"
    odom_frame: "odom"

    # Topics
    scan_topic: "/scan"
    odom_topic: "/odom"
    cmd_vel_topic: "/cmd_vel"
    local_costmap_topic: "/local_costmap/costmap"