<!--
Copyright (c) 2024 Michael Wimble
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="gazebo_wheels" params="instances:=^*">
    <xacro:if value="${instances}">
      <xacro:property name="instance" value="${instances.pop(0)}"/>
      <xacro:element xacro:name="${instance['name']}_joint">${instance['name']}_wheel_joint</xacro:element>
      <xacro:gazebo_wheels instances="${instances}"/>
    </xacro:if>
  </xacro:macro>
  <xacro:macro name="gazebo_joints" params="instances:=^*">
    <xacro:if value="${instances}">
      <xacro:property name="instance" value="${instances.pop(0)}"/>
      <joint_name>${instance['name']}_wheel_joint</joint_name>
      <xacro:gazebo_joints instances="${instances}"/>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="diff_drive_controller" params="config instances1 instances2">

    <gazebo>
      <plugin name="gz::sim::systems::DiffDrive" filename="gz-sim-diff-drive-system">

        <!-- Wheel Information -->
        <xacro:gazebo_wheels instances="${instances1}"/>
        <wheel_separation>${(config.body.radius - config.wheels.center_offset) * 2}</wheel_separation>
        <wheel_radius>${config.wheels.radius}</wheel_radius>

        <!-- Limits -->
        <!-- <max_wheel_torque>200</max_wheel_torque> -->
        <max_linear_acceleration>1.0</max_linear_acceleration>

        <!-- Input -->
        <topic>cmd_vel</topic>


        <!-- Output -->
        <frame_id>odom</frame_id>
        <child_frame_id>base_link</child_frame_id>
        <odom_topic>odom</odom_topic>
        <odom_publisher_frequency>50</odom_publisher_frequency>

        <tf_topic>/tf</tf_topic>

      </plugin>

      <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
        <topic>joint_states</topic>
        <xacro:gazebo_joints instances="${instances2}"/>
      </plugin>

        <!-- GROUND ODOMETRY POSITION STATE PUBLISHER (FAKE LOCALIZATION) -->
        <plugin filename="ignition-gazebo-pose-publisher-system" name="ignition::gazebo::systems::PosePublisher">
            <publish_link_pose>true</publish_link_pose>
            <publish_collision_pose>false</publish_collision_pose>
            <publish_visual_pose>false</publish_visual_pose>
            <publish_sensor_pose>false</publish_sensor_pose>
            <publish_nested_model_pose>true</publish_nested_model_pose>
            <update_frequency>20</update_frequency>
        </plugin>
    </gazebo>
  </xacro:macro>
</robot>