<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ld06">

  <xacro:macro name="ld06" params="lidar_prefix topic_name:=scan *joint_pose">
    <material name="ld06_${lidar_prefix}_grey">
      <color rgba="0.3 0.3 0.3 1" />
    </material>

    <material name="ld06_${lidar_prefix}_blackish">
      <color rgba="0.1 0.1 0.1 1" />
    </material>

    <material name="ld06_${lidar_prefix}_cylinder">
      <color rgba="0.05 0.05 0.2 1" />
    </material>

    <xacro:property name="ld06_base_box_height" value="0.011" />
    <xacro:property name="ld06_base_box_width" value="0.060" />
    <xacro:property name="ld06_box_width" value="0.037" />
    <xacro:property name="ld06_box_height" value="0.020" />
    <xacro:property name="ld06_cylinder_height" value="0.012" />
    <xacro:property name="ld06_cylinder_radius" value="0.015" />

    <joint name="base_to_lidar_frame_${lidar_prefix}" type="fixed">
      <parent link="base_link" />
      <child link="lidar_frame_${lidar_prefix}" />
      <xacro:insert_block name="joint_pose" />
    </joint>

    <link name="lidar_frame_${lidar_prefix}">
      <collision>
        <origin xyz="0 0 ${ld06_base_box_height / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${ld06_base_box_width} ${ld06_base_box_width / 2} ${ld06_base_box_height}" />
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 ${ld06_base_box_height / 2}" rpy="0 0 0" />
        <geometry>
          <box size="${ld06_base_box_width} ${ld06_base_box_width / 2} ${ld06_base_box_height}" />
        </geometry>
        <material name="ld06_${lidar_prefix}_grey" />
      </visual>

      <visual>
        <origin xyz="0 0.017 ${ld06_base_box_height + (ld06_box_height / 2)}" rpy="0 0 0" />
        <geometry>
          <box size="${ld06_box_width} ${ld06_box_width} ${ld06_box_height}" />
        </geometry>
        <material name="ld06_${lidar_prefix}_blackish" />
      </visual>

      <visual>
        <origin xyz="0 0.017 ${(ld06_base_box_height + ld06_box_height) +(ld06_cylinder_height / 2)}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${ld06_cylinder_radius}" length="${ld06_cylinder_height}" />
        </geometry>
        <material name="ld06_${lidar_prefix}_cylinder" />
      </visual>

      <visual>
        <geometry>
          <cylinder radius="${ld06_base_box_width / 2}" length="${ld06_base_box_height}" />
        </geometry>
        <material name="ld06_${lidar_prefix}_grey" />
        <origin xyz="0 ${ld06_base_box_width / 4} ${(ld06_base_box_height / 2)}" rpy="0 0 0" />
      </visual>

      <xacro:solid_cuboid_inertial rpy="0 0 0" xyz="0 0 0" mass_kg="0.001" x="${ld06_base_box_width}" y="${ld06_base_box_width / 2}" z="${ld06_base_box_height}" />
    </link>

    <link name="lidar_beam_${lidar_prefix}"></link>
    <joint name="laser_beam_${lidar_prefix}_joint" type="fixed">
      <parent link="lidar_frame_${lidar_prefix}" />
      <child link="lidar_beam_${lidar_prefix}" />
      <origin xyz="0 0 0.04" rpy="0 0 0" />
    </joint>

    <gazebo reference="lidar_frame_${lidar_prefix}">
      <material>Gazebo/Black</material>

      <sensor name="lidar_frame_${lidar_prefix}" type="gpu_lidar">
        <visualize>true</visualize>
        <update_rate>10</update_rate>
        <lidar>
          <scan>
            <horizontal>
              <samples>450</samples>
              <resolution>1</resolution>
              <min_angle>-3.14159</min_angle>
              <max_angle>3.14159</max_angle>
            </horizontal>
            <vertical>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </vertical>
          </scan>
          <range>
            <min>0.3</min>
            <max>12.0</max>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
          <!-- Add ray filtering to handle self-collisions -->
          <ray>
            <scan>
              <horizontal>
                <samples>450</samples>
                <resolution>1</resolution>
                <min_angle>-3.14159</min_angle>
                <max_angle>3.14159</max_angle>
              </horizontal>
            </scan>
            <range>
              <min>0.3</min>
              <max>12.0</max>
            </range>
          </ray>
        </lidar>
        <topic>${topic_name}</topic>
        <gz_frame_id>lidar_beam_${lidar_prefix}</gz_frame_id>
      </sensor>

      <!-- Use correct Gazebo Garden/Harmonic plugin -->
      <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_gpu_laser.so">
        <ros>
          <namespace></namespace>
          <remapping>~/out:=${topic_name}</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_beam_${lidar_prefix}</frame_name>
      </plugin>
    </gazebo>
  </xacro:macro>

  <!--
Copyright (c) 2025 Michael Wimble
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->

</robot>