<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="Sigyn">
  <self_collide>false</self_collide>
  <pose>0 0 0.2 0 0 0</pose>
  <static>false</static>
  <xacro:arg name="use_ros2_control" default="true" />
  <xacro:arg name="sim_mode" default="false" />

  <xacro:include filename="$(find description)/urdf/common_macros.xacro" />
  <xacro:include filename="$(find description)/urdf/inertials.xacro" />
  <xacro:property name="props" value="${xacro.load_yaml('sigyn_config.yaml')}" />
  <xacro:include filename="$(find description)/urdf/sigyn_base_macro.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/sigyn_caster_wheel_macro.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/sigyn_wheels_macro.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/oakd.urdf.xacro" />

  <xacro:if value="$(arg use_ros2_control)">
    <xacro:include filename="ros2_control.xacro" />
  </xacro:if>

  <!-- <xacro:unless value="$(arg use_ros2_control)">
    <xacro:include filename="gazebo_control.xacro" />
  </xacro:unless> -->
  
  <!-- Make the body-->
  <xacro:sigyn_base body_props="${props.body}" wheels_props="${props.wheels}" />

  <!-- Make the wheels-->
  <xacro:wheels config="${props}" instances="${props.wheels.instances}" />

  <!-- Make the caster wheel -->
  <xacro:caster_wheel config="${props}" />

  <xacro:include filename="$(find description)/urdf/ld06.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/gazebo.urdf.xacro" />
  <xacro:ld06 lidar_prefix="top_lidar">
    <origin xyz="0.155 0 0.300" rpy="0 0 -${pi / 2}" />
  </xacro:ld06>

  <xacro:include filename="$(find description)/urdf/gripper_assembly.urdf.xacro" />
  <joint name="base_link_to_elevator_pole" type="fixed">
    <origin xyz="-0.16 -0.015 ${0.3 + (elevator_pole_height/2)}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="evelator_pole" />
  </joint>

  <!-- <xacro:oakd_link mount_point="elevator_top" /> -->
  <xacro:oakd_joint mount_point="elevator_top">
    <origin xyz="-0.12 -0.02 1.47" rpy="0 ${(pi / 4)+13*(2.0*pi/360.0)} ${-0*(2.0*pi/360.0)}" /> <!--was 1.45 -->
  </xacro:oakd_joint>

  <gazebo>
    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>elevator_pole_to_elevator_connector_plate</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/elevator_connector_plate/position</topic>
    </plugin>

    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>gripper_elevator_plate_to_gripper_extender</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/gripper_elevator_plate_to_gripper_extender/position</topic>
    </plugin>

    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>gripper_wrist_to_parallel_gripper_base_plate</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/gripper_wrist_to_parallel_gripper_base_plate/position</topic>
    </plugin>

    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>parallel_gripper_base_plate_to_left_finger</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/parallel_gripper_base_plate_to_left_finger/position</topic>
    </plugin>

    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>parallel_gripper_base_plate_to_right_finger</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/parallel_gripper_base_plate_to_right_finger/position</topic>
    </plugin>

  </gazebo>

  <xacro:diff_drive_controller config="${props}" instances1="${props.wheels.instances}"
    instances2="${props.wheels.instances}" />
</robot>