<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="caster_wheel_upright" params="config name y_offset_multiplier">
    <xacro:property name="chassis_bottom" value="${config.wheels.radius + (config.wheels.gear_box_height / 2) + config.wheels.gear_box_spacing_from_base}" />
    <xacro:property name="upright_width" value="0.01" />
    <link name="caster_frame_${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${chassis_bottom - config.caster.radius} ${upright_width} 0.005" />
        </geometry>
        <material name="caster_upright_color">
          <color rgba="0.7 0.7 0.72 1.0" />
        </material>
      </visual>
    </link>

    <gazebo reference="caster_frame_${name}">
      <visual>
        <material>
          <ambient>0.7 0.7 0.72 1.0</ambient>
          <diffuse>0.7 0.7 0.72 1.0</diffuse>
          <specular>0.7 0.7 0.72 1.0</specular>
          <emissive>0.0 0.0 0.0 0.0</emissive>
        </material>
      </visual>
    </gazebo>

    <joint name="caster_frame_${name}_joint" type="fixed">
      <parent link="chassis" />
      <child link="caster_frame_${name}" />
      <origin xyz="${-(config.body.radius - config.caster.x_offset)} ${((upright_width/2) + (config.caster.width/2)) * y_offset_multiplier} -${chassis_bottom - config.caster.radius - (chassis_bottom - config.caster.radius)/2}" rpy="${pi/2} ${pi/2} 0" />
    </joint>
  </xacro:macro>

  <xacro:macro name="caster_wheel" params="config">
    <xacro:property name="caster_radius" value="0.025" />
    <xacro:property name="caster_width" value="0.023" />
    <xacro:property name="caster_offset" value="0.035" />
    <xacro:property name="caster_wheel_x" value="${-(body_radius-caster_offset)}" />

    <link name="caster_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${config.caster.radius}" length="${config.caster.width}" />
        </geometry>
        <material name="red">
          <color rgba="0.416 0.051 0.047 1.0" />
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${config.caster.radius}" length="${config.caster.width}" />
        </geometry>
      </collision>

      <xacro:solid_cylinder_inertial rpy="0 0 0" xyz="0 0 0" mass_kg="${config.caster.mass}" radius="${config.caster.radius}" length="${config.caster.width}" />
    </link>

    <gazebo reference="caster_wheel_link">
      <mu1>0.01</mu1>
      <mu2>0.01</mu2>
      <visual>
        <material>
          <ambient>0.416 0.051 0.047  1.0</ambient>
          <diffuse>0.416 0.051 0.047  1.0</diffuse>
          <specular>0.416 0.051 0.047  1.0</specular>
          <emissive>0.0 0.0 0.0 0.0</emissive>
        </material>
      </visual>
    </gazebo>

    <joint name="caster_wheel_joint" type="fixed">
      <parent link="chassis" />
      <child link="caster_wheel_link" />
      <origin xyz="${-(config.body.radius - config.caster.x_offset)} 0 -${config.wheels.radius + (config.wheels.gear_box_height / 2) -config.caster.radius + config.wheels.gear_box_spacing_from_base}" rpy="${pi/2} 0 0" />
    </joint>

    <xacro:caster_wheel_upright config="${config}" name="left" y_offset_multiplier="1" />
    <xacro:caster_wheel_upright config="${config}" name="right" y_offset_multiplier="-1" />
  </xacro:macro>

  <!--
Copyright (c) 2024 Michael Wimble
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->

</robot>