<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sigyn_base" params="body_props wheels_props">
    <!-- base_link -->
    <link name="base_link" />
    <joint name="base_to_chassis" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <child link="chassis" />
      <parent link="base_link" />
    </joint>

    <link name="chassis">
      <collision>
        <geometry>
          <cylinder radius="${body_props.radius}" length="${body_props.height}" />
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 ${(body_props.height/2)}" />
      </collision>
      <visual>
        <geometry>
          <cylinder radius="${body_props.radius}" length="${body_props.height}" />
        </geometry>
        <material name="body_aluminum" />
        <origin rpy="0 0 0" xyz="0 0 ${(body_props.height / 2)}" />
      </visual>
      <xacro:solid_cylinder_inertial rpy="0 0 0" xyz="-0.05 0 0.05" mass_kg="${body_props.mass}" radius="${body_props.radius}" length="${body_props.height}" />
    </link>

    <!-- base_footprint -->
    <link name="base_footprint" />
    <joint name="base_footprint_to_base_link" type="fixed">
      <origin xyz="0 0 -${wheels_props.radius + (wheels_props.gear_box_height / 2) + wheels_props.gear_box_spacing_from_base}" rpy="0 0 0" />
      <child link="base_footprint" />
      <parent link="base_link" />
    </joint>

    <material name="body_aluminum">
      <color rgba="0.516 0.527 0.535 1" />
    </material>

    <gazebo reference="chassis">
      <material>
      Gazebo/Grey
      </material>
    </gazebo>

  </xacro:macro>

</robot>
<!--
Copyright (c) 2024 Michael Wimble
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
