<?xml version="1.0"?>
<!--
Copyright (c) 2024 Michael Wimble
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="wheel" params="axis side radius width pos_x pos_y pos_z mass_kg">
    <!-- Create the outer, rubber tire -->
    <xacro:colorize_link color="0.15 0.15 0.15 1.0" name="${side}_wheel_link">
      <foo>
        <visual name="tire">
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <cylinder radius="${radius}" length="${width - 0.004}" />
          </geometry>
          <material name="${side}_wheel_link"/>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
          <geometry>
            <cylinder radius="${radius}" length="${width}" />
          </geometry>
        </collision>
        <xacro:solid_cylinder_inertial rpy="${pi/2} 0 0" xyz="0 0 0" mass_kg="${mass_kg}" radius="${radius}" length="${width}" />
      </foo>
    </xacro:colorize_link>

    <joint name="${side}_wheel_joint" type="continuous">
      <axis xyz="0 0 ${axis}" />
      <parent link="base_link" />
      <child link="${side}_wheel_link" />
      <origin xyz="${pos_x} ${pos_y} ${pos_z}" rpy="${-axis * pi / 2} 0 0" />
    </joint>

    <!-- Create the wheel hub -->
    <xacro:colorize_link color="0.8 0.8 0.8 1.0" name="${side}_wheel_hub">
      <foo>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <visual>
          <geometry>
            <cylinder radius="${radius - 0.02}" length="${width - 0.002}" />
          </geometry>
          <material name="${side}_wheel_hub"/>
        </visual>
      </foo>
    </xacro:colorize_link>

    <joint name="${side}_wheel_hub_joint" type="fixed">
      <axis xyz="0 0 ${axis}" />
      <parent link="${side}_wheel_link" />
      <child link="${side}_wheel_hub" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <!-- Create the wheel marker -->
    <xacro:colorize_link color="0.86 0.54 0.86 1" name="${side}_wheel_marker">
      <foo>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <visual>
          <geometry>
            <box size="0.01 ${(radius / 2)} ${width}" />
          </geometry>
          <material name="${side}_wheel_marker"/>
        </visual>
      </foo>
    </xacro:colorize_link>

    <joint name="${side}_wheel_marker_joint" type="fixed">
      <parent link="${side}_wheel_hub" />
      <child link="${side}_wheel_marker" />
      <origin xyz="0 ${(radius - 0.02) / 2} 0" rpy="0 0 0" />
    </joint>

  </xacro:macro>

  <xacro:macro name="wheels" params="config instances:=^*">
    <xacro:if value="${instances}">
      <!-- pop first item from list -->
      <xacro:property name="instance" value="${instances.pop(0)}"/>
      <xacro:property name="y" value="${(config.body.radius-config.wheels.center_offset)*instance['y_position_multiplier']}"/>
      <xacro:property name="z" value="-${(config.wheels.gear_box_height/2)+config.wheels.gear_box_spacing_from_base}"/>
      <xacro:wheel axis="${instance['y_position_multiplier']}" pos_y="${y}" pos_z="${z}" side="${instance['name']}" radius="${config.wheels.radius}" width="${config.wheels.width}" pos_x="0.0" mass_kg="${config.wheels.mass}" />
      <xacro:wheels config="${config}" instances="${instances}"/>
    </xacro:if>
  </xacro:macro>
</robot>
