<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="Sigyn">
  <xacro:arg name="use_ros2_control" default="true" />
  <xacro:arg name="sim_mode" default="false" />

  <xacro:include filename="$(find description)/urdf/common_macros.xacro" />
  <xacro:include filename="$(find description)/urdf/inertials.xacro" />
  <xacro:property name="props" value="${xacro.load_yaml('sigyn_config.yaml')}" />
  <xacro:include filename="$(find description)/urdf/sigyn_base_macro.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/sigyn_caster_wheel_macro.urdf.xacro" />
  <xacro:include filename="$(find description)/urdf/sigyn_wheels_macro.urdf.xacro" />

  <xacro:unless value="$(arg sim_mode)">
    <xacro:include filename="$(find description)/urdf/depthai_macro.urdf.xacro" />
  </xacro:unless>

  <!-- <xacro:unless value="$(arg sim_mode)"> -->
    <xacro:include filename="$(find description)/urdf/oakd.urdf.xacro" />
  <!-- </xacro:unless> -->

  <!-- <xacro:if value="$(arg sim_mode)">
    <xacro:include filename="$(find description)/urdf/oakd_sim.urdf.xacro" />
  </xacro:if> -->

  <xacro:if value="$(arg use_ros2_control)">
    <xacro:include filename="ros2_control.xacro" />
  </xacro:if>

  <!-- <xacro:unless value="$(arg use_ros2_control)">
    <xacro:include filename="gazebo_control.xacro" />
  </xacro:unless> -->

  <!-- Make the body-->
  <xacro:sigyn_base body_props="${props.body}" wheels_props="${props.wheels}" />

  <!-- Make the wheels-->
  <xacro:wheels config="${props}" instances="${props.wheels.instances}" />

  <!-- Make the caster wheel -->
  <xacro:caster_wheel config="${props}" />

  <xacro:include filename="$(find description)/urdf/ld06.urdf.xacro" />

  <xacro:ld06 lidar_prefix="top_lidar" topic_name="scan">
    <origin xyz="0.155 0 0.300" rpy="0 0 -${pi / 2}" />
  </xacro:ld06>

  <xacro:ld06 lidar_prefix="cup_lidar" topic_name="scan_cup">
    <!-- <origin xyz="${0.15-0.34} 0 ${0.300+1.485}" rpy="0 0 0" /> -->
    <origin xyz="-0.161 -0.015 ${0.300 + 1.485 - 0.032}" rpy="0 0 0" />
  </xacro:ld06>

  <xacro:include filename="$(find description)/urdf/gazebo.urdf.xacro" />

  <xacro:include filename="$(find description)/urdf/gripper_assembly.urdf.xacro" />
  <joint name="base_link_to_elevator_pole" type="fixed">
    <origin xyz="-0.16 0 ${0.3 + (elevator_pole_height/2)}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="evelator_pole" />
  </joint>

  <!-- <xacro:oakd_link mount_point="elevator_top" /> -->
  <xacro:oakd_joint mount_point="elevator_top">
    <!-- <origin xyz="-0.12 -0.02 1.47" rpy="0 ${(pi / 4)+13*(2.0*pi/360.0)} ${-0*(2.0*pi/360.0)}" /> -->
    <!-- <origin xyz="-0.12 -0.02 1.7" rpy="0 ${pi / 4} -1.029" /> -->
    <!-- <origin xyz="-0.09 0.015 1.65" rpy="${-pi / 2} ${(-pi / 2) + 1.029} 0" /> -->
    <origin xyz="-0.09 0.0 1.65" rpy="${-pi / 2} ${(-pi / 2) + 1.029} 0" />
  </xacro:oakd_joint>

  <gazebo>
    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>elevator_pole_to_elevator_connector_plate</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/elevator_connector_plate/position</topic>
    </plugin>

    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>gripper_elevator_plate_to_gripper_extender</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/gripper_elevator_plate_to_gripper_extender/position</topic>
    </plugin>

    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>gripper_wrist_to_parallel_gripper_base_plate</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/gripper_wrist_to_parallel_gripper_base_plate/position</topic>
    </plugin>

    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>parallel_gripper_base_plate_to_left_finger</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/parallel_gripper_base_plate_to_left_finger/position</topic>
    </plugin>

    <plugin filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>parallel_gripper_base_plate_to_right_finger</joint_name>
      <p_gain>1.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <i_max>0.0</i_max>
      <i_min>0.0</i_min>

      <cmd_max>1</cmd_max>
      <cmd_min>-1</cmd_min>
      <topic>/parallel_gripper_base_plate_to_right_finger/position</topic>
    </plugin>

  </gazebo>

  <xacro:diff_drive_controller config="${props}" instances1="${props.wheels.instances}"
    instances2="${props.wheels.instances}" />

  <!-- IMU0 - Upside down & backwards -->
  <joint name="imu0_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu_0" />
    <origin xyz="-0.100 0.180 0.022" rpy="0 3.14159 3.14159" />
  </joint>

  <link name="imu_0" />

  <!-- IMU1 - Right-side up & backwards -->
  <joint name="imu1_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu_1" />
    <origin xyz="0.085 -0.185 0.022" rpy="0 0 3.14159" />
  </joint>

  <link name="imu_1" />
  <xacro:include filename="$(find description)/urdf/vl53l0x.xacro" />
</robot>